FROM nginx
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y git
RUN apt-get install -y nano
RUN apt-get install -y gnupg
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get install -y build-essential
RUN sudo apt-get update
RUN apt-get install -y nodejs
RUN npm install -g yarn
RUN npm install -g angular-cli
